---
- name: Converge
  hosts: all
  become: true
  gather_facts: true

  roles:
    - role: set-hostname
      vars:
        input_debug: true
        input_hostname_fqdn: "test-{{ ansible_distribution | lower }}.rachuna-net.pl"
        input_disable_reboot: false
